import Foundation

/// Build-time identity for the running OFEM binary.
/// hash, build date, and the Application Insights connection string that
/// every OFEM build reports to.
///
/// Version is read from the main bundle's `CFBundleShortVersionString` at
/// runtime so that Xcode-built releases pick up the correct CalVer string
/// (e.g. `"2026.05.1"`) set by `xcconfig`. Falls back to `"0.0.0-dev"` in
/// unit-test contexts where `Bundle.main` is the `xctest` runner and no
/// version key is set.
///
/// Commit and date are injected via Xcode build settings
/// (`SWIFT_ACTIVE_COMPILATION_CONDITIONS` or a generated `BuildInfoConstants.swift`)
/// in official release builds. They are empty strings in source builds and
/// during testing.
public enum BuildInfo {
    // MARK: - Version

    /// The CalVer release string (e.g. `"2026.05.1"`).
    ///
    /// Read from `CFBundleShortVersionString` in `Bundle.main`. Falls back
    /// to `"0.0.0-dev"` when the key is absent (xctest, command-line tool
    /// builds, or un-versioned debug builds).
    public static let version: String = {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString")
            as? String ?? "0.0.0-dev"
    }()

    /// The short git commit SHA injected at build time.
    ///
    /// Set by the Xcode pre-build script via a Swift constant in
    /// `BuildInfoConstants.swift`. Empty string in plain `swift build` and
    /// unit tests.
    public static let commit: String = _BuildInfoConstants.commit

    /// The ISO-8601 build timestamp injected at build time.
    ///
    /// Set by the Xcode pre-build script via a Swift constant in
    /// `BuildInfoConstants.swift`. Empty string in plain `swift build` and
    /// unit tests.
    public static let date: String = _BuildInfoConstants.date

    // MARK: - Telemetry

    /// The Application Insights connection string used for opt-out telemetry.
    ///
    /// This is a committed source constant — identical to
    /// `buildinfo.AppInsightsConnString` in the Go package. It is deliberately
    /// public and committed: App Insights connection strings are write-only by
    /// design and ship inside every browser-side JS app, mobile binary, and
    /// desktop app that uses Application Insights. Committing it here means that
    /// source builds and forks report to the same endpoint as official Homebrew
    /// releases, so the maintainer sees a representative signal.
    ///
    /// Users disable telemetry from the menu bar (Settings › Telemetry) or by
    /// setting `OFEM_TELEMETRY=0`. No opt-in path requires editing this file.
    public static let appInsightsConnectionString =
        "InstrumentationKey=bb7c05e2-4616-4b8d-a18a-e32128034eb4;" +
        "IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;" +
        "LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/;" +
        "ApplicationId=427c95d5-7252-4513-aed3-e1e5c3eece9d"
}

// MARK: - Build-time constants shim

/// Internal namespace for build-time constants generated by the Xcode
/// pre-build script (`scripts/generate-buildinfo.sh`). In source builds and
/// tests these default to empty strings, matching the Go behaviour
/// (`var Commit = ""` / `var Date = ""`).
///
/// The generated file at `Packages/OfemKit/Sources/OfemKit/BuildInfo/BuildInfoConstants.swift`
/// is in `.gitignore`; the Xcode build phase writes it before compilation.
enum _BuildInfoConstants {
    static let commit: String = {
        // In Xcode release builds the generated file overrides this with the
        // real SHA. In source/test builds we return empty.
        return ""
    }()
    static let date: String = {
        return ""
    }()
}
