// Command ofem-docs regenerates the CLI reference under docs/cli/ and
// keeps the matching nav block in zensical.toml in sync with the
// cobra command tree.
//
// It walks the tree exposed by cmd/ofem/cli.NewRoot and writes one
// Markdown file per command using cobra's doc/ helper. The generator
// also rewrites the "CLI reference" navigation block in zensical.toml
// — delimited by `# --- BEGIN CLI NAV ---` / `# --- END CLI NAV ---`
// markers — so adding a new cobra command never requires a manual nav
// edit.
//
// Usage:
//
//	go run ./cmd/ofem-docs [output-dir]
//
// The default output directory is docs/cli/. The Makefile's docs-cli
// target invokes this generator and is itself a dependency of the docs
// build, so the published reference can never drift from the cobra
// tree (CI enforces a clean diff after running make docs-cli).
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/sdebruyn/onelake-explorer-macos/cmd/ofem/cli"
)

const (
	defaultOutDir   = "docs/cli"
	zensicalToml    = "zensical.toml"
	navBeginMarker  = "# --- BEGIN CLI NAV (generated by `make docs-cli`; do not edit by hand) ---"
	navEndMarker    = "# --- END CLI NAV ---"
	navTopLevelName = "CLI reference"
)

func main() {
	outDir := defaultOutDir
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}

	if err := run(outDir); err != nil {
		fmt.Fprintln(os.Stderr, "ofem-docs:", err)
		os.Exit(1)
	}
}

func run(outDir string) error {
	// filepath.Clean before use; the directory is taken from argv
	// in a developer-run tool, so this is purely about keeping
	// gosec quiet without changing behavior.
	outDir = filepath.Clean(outDir)
	if err := os.MkdirAll(outDir, 0o750); err != nil { //nolint:gosec // developer tool, outDir is argv
		return fmt.Errorf("create %s: %w", outDir, err)
	}

	root := cli.NewRoot()

	// Pin the rendered version string so the generated Markdown stays
	// stable across local builds (where buildinfo.Version is "dev")
	// and CI (where it's stamped via ldflags). The reference site is
	// about command shape, not the running binary's build metadata.
	root.Version = "see release notes"

	// Recursively suppress cobra's "Auto generated by spf13/cobra on
	// <date>" footer on every command in the tree. Without this the
	// output churns by one line per file every day and CI's diff
	// guard becomes useless.
	disableAutoGenTag(root)

	if err := doc.GenMarkdownTreeCustom(root, outDir, frontMatter, rewriteLink); err != nil {
		return fmt.Errorf("generate markdown tree: %w", err)
	}

	if err := updateNav(zensicalToml, root, outDir); err != nil {
		return fmt.Errorf("update nav in %s: %w", zensicalToml, err)
	}

	return nil
}

// disableAutoGenTag walks the whole command tree and turns off cobra's
// dated footer. GenMarkdownTreeCustom only checks the field on each
// command being rendered, so we have to set it everywhere up front.
func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGenTag(c)
	}
}

// frontMatter returns the YAML front matter that zensical / Material
// uses to title the page in the sidebar. Without an explicit title
// the nav entry defaults to the filename, which would read as
// "ofem_account" instead of "ofem account".
//
// filename is the absolute path of the markdown file cobra is about
// to write, e.g. ".../docs/cli/ofem_account_add.md".
func frontMatter(filename string) string {
	base := strings.TrimSuffix(filepath.Base(filename), ".md")
	title := strings.ReplaceAll(base, "_", " ")
	return fmt.Sprintf("---\ntitle: %s\n---\n\n", title)
}

// rewriteLink is the identity function: cobra generates intra-page
// links like "ofem_account.md" and that filename matches what we
// write to disk, so no rewriting is needed. We keep the hook so
// switching to a different filename scheme later is a one-liner.
func rewriteLink(s string) string {
	return s
}

// updateNav rewrites the block between navBeginMarker and navEndMarker
// in zensical.toml so the "CLI reference" sidebar entry always lists
// every cobra command. The rest of the file is left untouched. The
// generator round-trips raw text rather than parsing the TOML so the
// hand-curated formatting in the rest of the file (comments,
// alignment) survives.
func updateNav(tomlPath string, root *cobra.Command, outDir string) error {
	info, err := os.Stat(tomlPath)
	if err != nil {
		return fmt.Errorf("stat: %w", err)
	}
	raw, err := os.ReadFile(tomlPath)
	if err != nil {
		return fmt.Errorf("read: %w", err)
	}

	content := string(raw)
	beginIdx := strings.Index(content, navBeginMarker)
	endIdx := strings.Index(content, navEndMarker)
	if beginIdx < 0 || endIdx < 0 || endIdx < beginIdx {
		return fmt.Errorf("could not find %q / %q markers — restore them and rerun", navBeginMarker, navEndMarker)
	}

	// Detect the indentation prefix of the BEGIN marker line so the
	// regenerated block reuses the same indentation as the rest of
	// the nav array.
	lineStart := strings.LastIndex(content[:beginIdx], "\n") + 1
	indent := content[lineStart:beginIdx]

	commands := collectCommands(root, outDir)
	block := renderNavBlock(commands, indent)

	endLineEnd := strings.Index(content[endIdx:], "\n")
	if endLineEnd < 0 {
		endLineEnd = len(content) - endIdx
	}
	endLineEnd += endIdx

	newContent := content[:lineStart] + block + content[endLineEnd:]
	if newContent == content {
		return nil
	}

	// Preserve the existing file mode (typically 0644 when committed
	// to git). Hard-coding a stricter mode would silently mutate the
	// on-disk permissions every regeneration run.
	return os.WriteFile(tomlPath, []byte(newContent), info.Mode().Perm()) //nolint:gosec // mode mirrors the existing file
}

// navEntry is one line of the rendered nav array.
type navEntry struct {
	Title string
	Path  string
}

// collectCommands walks the command tree depth-first in
// CommandPath() order so the nav lists `ofem`, then each subcommand
// alphabetically, then its children. The order matches cobra's own
// SEE ALSO sections and reads naturally in the sidebar.
func collectCommands(root *cobra.Command, outDir string) []navEntry {
	var out []navEntry
	walk(root, outDir, &out)
	return out
}

func walk(cmd *cobra.Command, outDir string, out *[]navEntry) {
	if cmd.HasParent() && !cmd.IsAvailableCommand() {
		return
	}
	if cmd.IsAdditionalHelpTopicCommand() {
		return
	}

	path := cmd.CommandPath()
	basename := strings.ReplaceAll(path, " ", "_") + ".md"

	// Nav paths are relative to docs/ (the project's docs_dir), so
	// strip a leading "docs/" segment from outDir if present. The
	// other nav entries in zensical.toml use the same convention
	// (e.g. "cli/ofem.md", not "docs/cli/ofem.md").
	navDir := strings.TrimPrefix(filepath.ToSlash(outDir), "docs/")
	*out = append(*out, navEntry{
		Title: path,
		Path:  filepath.ToSlash(filepath.Join(navDir, basename)),
	})

	children := append([]*cobra.Command(nil), cmd.Commands()...)
	sort.Slice(children, func(i, j int) bool {
		return children[i].Name() < children[j].Name()
	})
	for _, c := range children {
		walk(c, outDir, out)
	}
}

// renderNavBlock writes the BEGIN/END-delimited TOML block. The
// indent argument is whatever whitespace prefixes the BEGIN marker
// line in the existing file, so the regenerated block stays aligned
// with the surrounding nav entries.
func renderNavBlock(entries []navEntry, indent string) string {
	var buf bytes.Buffer
	buf.WriteString(indent)
	buf.WriteString(navBeginMarker)
	buf.WriteString("\n")
	buf.WriteString(indent)
	fmt.Fprintf(&buf, "{ %q = [\n", navTopLevelName)
	for _, e := range entries {
		buf.WriteString(indent)
		buf.WriteString("  ")
		fmt.Fprintf(&buf, "{ %q = %q },\n", e.Title, e.Path)
	}
	buf.WriteString(indent)
	buf.WriteString("] },\n")
	buf.WriteString(indent)
	buf.WriteString(navEndMarker)
	return buf.String()
}
