// Package daemon hosts the long-running OFE background process. It
// owns the SQLite metadata cache, the IPC server, and (in later PRs)
// the sync engine that polls Fabric for changes and drives the File
// Provider Extension via XPC.
//
// The daemon is meant to run under a LaunchAgent (see
// dev.debruyn.ofe.daemon.plist generated by `ofe daemon install`) but
// can also be invoked directly with `ofe daemon run` for development.
package daemon
